### ISSUE TITLE
pytorch 1.6 support?

### ISSUE THREAD

**Issue by eric-haibin-lin** [IBM/pytorch-large-model-support#4]
Pytorch 1.6 is released. Is there a plan to release the support for PT 1.6?

**Comment by jayfurmanek** [comment]
Hi! Thanks for your interest!

Unfortuantely, We no longer have the resources to maintain LMS on PyTorch. We tried very hard to upstream this code, but it's very difficult to merge code into projects that are not openly governed. 
I'd be happy to host any new patches for 1.6 here if anyone wanted to work on it, however.
